const dc_parent_medical = "Include expenses to care for parents, i.e. through carer, for parents who suffer from diseases, physical or mental disabilities and need regular treatment certified by qualified medical practitioner. Include treatment and care at home, day care centres or home care centres.";
const dc_annuity = "Annuity Scheme Premium / Private Retirement Scheme (PRS)";
// const dc_edu_med_insurance = "";
const dc_edu_fees = "Other than a degree at masters or doctorate level - Course of study in law, accounting, islamic financing, technical, vocational, industrial, scientific or technology'</li><li>'Degree at masters or doctorate level - Any course of study</li><li>Any course of study undertaken for the purpose of up-skilling or self-enhancement recognized by the Director General of Skills Development under the National Skills Development Act 2006. (Restricted to 1,000)</li></ul>";
const dc_supporting_equipment = `Supporting
 equipment for disabled self / spouse / child / parent`;
const dc_medical_expenses = "<ul><li>Medical expenses on <b>serious diseases</b> includes the treatment of acquired immune deficiency syndrome (AIDS), Parkinson disease, cancer, renal failure, leukaemia and other similar diseases such as heart attack, pulmonary hypertension, chronic liver disease, fulminant viral hepatitis, head trauma with neurological deficit, brain tumour or vascular malinformation, major burns, major organ transplant and major amputation of limbs. Amount expended on own self, husband / wife or child is deductible up to a maximum of RM6,000 but total relief allowable for both items, F6 and F7 is restricted to RM6,000.</li><li>Medical expenses for <b>fertility treatment</b> for self or spouse</li>	<li>Vaccination expenses for self, spouse and child. Types of vaccine which qualify for deduction are as follows:<ol><li>Pneumococcal;</li><li>Human papillomavirus (HPV);</li><li>Influenza;</li><li>Rotavirus;</li><li>Varicella;</li><li>Meningococcal;</li><li>TDAP combination ( tetanus-diphtheria-acellular-pertussis); and</li><li>Coronavirus Disease 2019 (Covid-19)</li></ol>(Restricted to 1,000)</li><li><b>Complete medical examination</b> & COVID-19 detection test and vaccination expenses for self, spouse, child (Restricted to 1000)</li></ul>";
const dc_lifestyle = "Expenses for the use / benefit of self, spouse or child on purchase of: <ul><li>Books, journals, magazines and printed daily newspapers</li><li>Sport equipment (refer Sports Development Act 1997)</li><li>Computer, smartphone and tablet</li><li>Subscription of broadband internet / internet subscription</li><li>Gymnasium membership</li></ul>";
const dc_lifestyle_add = "Purchase of personal computer, smartphone or tablet for self, spouse or child and not for business use<br><br>This deduction is an addition to the deduction granted under item 10.";
const dc_lifestyle_sports = "Additional lifestyle tax relief related to sports activity expended by that individual for the following:<ul><li>Purchase of sport equipment for any sports activity as defined under the Sport Development Act 1997 (excluding motorized two-wheel bicycles);</li><li>Payment of rental or entrance fee to any sports facility; and</li><li>Payment of registration fee for any sports competition where the organizer is approved and licensed by the Commissioner of Sports under the Sport Development Act 1997.</li></ul>";
const dc_domestic_travel = "Payment for accommodation at premises registered with the Commissioner of Tourism and entrance fee to a tourist attraction<br><br><b>(Expenses incurred on or after 1st March 2020 until 31st December 2021)</b>";
const dc_zakat = "<b>Obligatory payment under Islamic law</b>";

